### ISSUE TITLE
ReferenceError: __P_105_0 is not defined on first load

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qxl.playground#3]
When opening https://qooxdoo.org/qxl.playground/ the following error is displayed is the native console and the application log:

```
Unfortunately, an unrecoverable internal error was caused by your code. This may prevent the playground application to run properly. ReferenceError: __P_105_0 is not defined
```

Tested with latest Firefox, Safari, Chrome  on MacOS 11.0.1

**Comment by goldim** [comment]
@cboulanger I don't see the error anymore could I close it?

**Comment by cboulanger** [comment]
Yes, please. Thanks!
